#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(WATER_PULSE) \
    F(DRAGON_CLAW) \
    F(SCALD) \
    F(PSYSHOCK) \
    F(ROAR) \
    F(TOXIC) \
    F(WILL_O_WISP) \
    F(LOW_SWEEP) \
    F(MAGICAL_LEAF) \
    F(HIDDEN_POWER) \
    F(ME_FIRST) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(ICY_WIND) \
    F(DUAL_WINGBEAT) \
    F(ROCK_BLAST) \
    F(PSYCHIC_FANGS) \
    F(CHILLING_WATER) \
    F(ENERGY_BALL) \
    F(DRAINING_KISS) \
    F(STOMPING_TANTRUM) \
    F(SOLAR_BEAM) \
    F(IRON_HEAD) \
    F(THUNDERBOLT) \
    F(SEED_BOMB) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DARK_PULSE) \
    F(BREAKING_SWIPE) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(ROCK_SLIDE) \
    F(HYPER_VOICE) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(POWER_GEM) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(X_SCISSOR) \
    F(FEINT_ATTACK) \
    F(SMART_STRIKE) \
    F(SKILL_SWAP) \
    F(FLASH_CANNON) \
    F(EARTH_POWER) \
    F(GRASSY_GLIDE) \
    F(LASH_OUT) \
    F(POWER_TRIP) \
    F(WILD_CHARGE) \
    F(BUG_BITE) \
    F(DAZZLING_GLEAM) \
    F(TRI_ATTACK) \
    F(HURRICANE) \
    F(BULLDOZE) \
    F(ICICLE_SPEAR) \
    F(LIQUIDATION) \
    F(POISON_JAB) \
    F(PSYCHO_CUT) \
    F(SHADOW_CLAW) \
    F(SIGNAL_BEAM) \
    F(STICKY_WEB) \
    F(SNARL) \
    F(TRAILBLAZE) \
    F(TRIPLE_AXEL) \
    F(VOLT_SWITCH) \
    F(U_TURN) \
    F(FLIP_TURN) \
    F(WEATHER_BALL) \
    F(OVERHEAT) \
    F(BUG_BUZZ) \
    F(BULLET_SEED) \
    F(ICE_PUNCH) \
    F(FIRE_PUNCH) \
    F(THUNDER_PUNCH) \
    F(TELEPORT) \
    F(CROSS_POISON) \
    F(AURA_SPHERE) \
    F(DRAGON_PULSE) \
    F(DUAL_CHOP) \
    F(PLAY_ROUGH) \
    F(FOLLOW_ME)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
